Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "bookId"
          "AttributeType": "S"
        - "AttributeName": "title"
          "AttributeType": "S"
        - "AttributeName": "author"
          "AttributeType": "S"
        - "AttributeName": "description"
          "AttributeType": "S"
        - "AttributeName": "infoLink"
          "AttributeType": "S"
        - "AttributeName": "finishedReading"
          "AttributeType": "BOOL"
        - "AttributeName": "imageLink"
          "AttributeType": "S"
        - "AttributeName": "category"
          "AttributeType": "S"

      "KeySchema":
        - "AttributeName": "bookId"
          "KeyType": "HASH"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "FavoriteBooks"
